get:
  tags:
    - product
  summary: 상품 목록 조회
  operationId: getProductList
  description: Returns a product List
  parameters:
    - $ref: '#/components/parameters/limit'
    - $ref: '#/components/parameters/offset'
    - $ref: '#/components/parameters/sort'
    - $ref: '#/components/parameters/search'
  responses:
    '200':
      description: (OK) 성공적으로 상품 목록 반환
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Product'
    '400':
      $ref: '#/components/responses/400BadRequest'
    '404':
      $ref: '#/components/responses/404NotFound'
    '500':
      $ref: '#/components/responses/GenericError'
post:
  tags:
    - product
  summary: 상품 등록
  operationId: postProductWithForm
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            name:
              description: '상품 이름'
              type: string
            description:
              description: '상품 설명'
              type: string
            price:
              description: '상품 가격'
              type: integer
            tags:
              description: '상품 태그'
              type: array
              items:
                type: string
          required:
            - name
            - description
            - price
            - tags
  responses:
    '201':
      description: (Created)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Product'
    '200':
      description: (OK)
    '204':
      $ref: '#/components/responses/204NoContent'
    '400':
      $ref: '#/components/responses/GenericError'
    '500':
      $ref: '#/components/responses/GenericError'
