get:
  tags:
    - product
  summary: 상품 댓글 목록 조회
  operationId: listProductComments
  parameters:
    - $ref: '#/components/parameters/productId'
    - $ref: '#/components/parameters/limit'
    - $ref: '#/components/parameters/cursor'
  responses:
    '200':
      description: (OK) 성공적으로 댓글 목록 반환
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Comment'
post:
  tags:
    - product
  summary: 상품 댓글 등록
  operationId: createProductComment
  parameters:
    - $ref: '#/components/parameters/productId'
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/CreateComment'
  responses:
    '201':
      description: (Created) 댓글 생성 성공
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Comment'
